name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v5
      - name: Run PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: Core/
          configuration: phpstan.dist
          level: 9
      - name: Run Codeception Tests
        run:  php vendor/bin/codecept run

